### ISSUE TITLE
Missing latitude and longitude

### ISSUE THREAD

**Issue by IdlePhysicist** [djbelieny/geoinfo-dataset#1]
I have noticed that 3447 rows in the full data set that contain longitude 0º and latitude 0º. I would like to know if there is an explanation for this fact. I would be interested in tracking down the missing data if I knew where it was gathered from initially. 

Do you have any information regarding this? I understand that this repo is not active but it's worth a try.

**Comment by djbelieny** [comment]
Sorry for the delayed response. No I do not have that info, maybe we need to write a script that runs combinations of state,city through some api like google maps and updates that info
