### ISSUE TITLE
Does Canada dataset has all locations present?

### ISSUE THREAD

**Issue by Sultan91** [djbelieny/geoinfo-dataset#2]
Hi, unfortunately, haven't found postcodes like 
```
K3S
- A9M
- C8Y
- T7F
- T9Q
- E3O
- E2D
- B6E
- G8U
- A7F
- V4Q
- X0S
- P8K
- G6U
- Y5V
- Y8G
- A5Q
- K5U
- H9D
- K9T
```

**Comment by djbelieny** [comment]
May not be complete since the sources may have been out of date. Feel free to add the ones you know about and maybe share a list of post codes you can find so that we can add to the list.
